plugins {
    id 'io.micronaut.build.internal.oraclecloud-kotlin-example'
    id 'io.micronaut.minimal.application'
}

dependencies {
    implementation(mn.micronaut.http.server.netty)
    implementation(mnReactor.micronaut.reactor)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mnSerde.micronaut.serde.support)
    implementation(projects.micronautOraclecloudBmcDatabase)
    implementation(projects.micronautOraclecloudBmcObjectstorage)
    runtimeOnly(mn.snakeyaml)
    runtimeOnly(mnLogging.logback.classic)
    testImplementation(libs.commons.lang3)
}

application {
    mainClass = 'example.ApplicationKt'
}

test {
    exclude '**/*Test$Intercepted*'
}
