:oracle-ojdbc-bom-version: 23.26.1.0.0

Oracle Cloud Autonomous Database connection information and credentials are stored in an https://docs.oracle.com/en-us/iaas/Content/Database/Tasks/adbconnecting.htm[Oracle Wallet].

Micronaut can automatically generate and download the Wallet and configure the data source.

First, you need the correct version of the Oracle Database driver and required modules.
To ensure you are using the correct version, apply the Oracle Database BOM. The following example uses 23.x BOM version {oracle-ojdbc-bom-version} with Gradle:

[source,groovy,subs=attributes+]
----
implementation platform("com.oracle.database.jdbc:ojdbc-bom:{oracle-ojdbc-bom-version}")
----

Or with Maven:

[source,xml,subs=attributes+]
----
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.oracle.database.jdbc</groupId>
        <artifactId>ojdbc-bom</artifactId>
        <version>{oracle-ojdbc-bom-version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
----

Second, add a dependency on the `micronaut-oraclecloud-atp` module:

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-atp[scope="runtime"]

Then configure the <<authentication, authentication provider>>.

Then, add a dependency to one of the Micronaut connection pool implementations.

NOTE: Automated configuration is currently supported only for the HikariCP and UCP connection pool.

dependency:micronaut-jdbc-ucp[groupId="io.micronaut.sql", scope="runtime"]

Or:

dependency:micronaut-jdbc-hikari[groupId="io.micronaut.sql", scope="runtime"]

NOTE: Note that `micronaut-oraclecloud-atp` module is compatible with Java 21+.

To use automated data source configuration from the Wallet, provide a configuration similar to the following:

[configuration]
----
datasources:
  default:
    ocid: ocid1.autonomousdatabase.oc1.....
    walletPassword: micronaut.1
    username: foo
    password: bar
----
- `ocid` specifies the Autonomous Database id
- `wallet-password` encrypts the keys inside the wallet. It must be at least eight characters long, include at least one letter, and either one numeric character or one special character)
- specify the database `username` and `password`
- optionally `service-alias-suffix` controls the suffix used when computing the default service alias using database name and given service alias suffix; defaults to `high` (e.g., set to `tp`)

NOTE: The `username` and `password` are not automatically generated and must be created in advance.

The module uses `(db_name + "_" + service-alias-suffix)` as the default service alias. By default, `service-alias-suffix` is `high`. You can override it (for example to `tp`). If `service-alias` is set, it takes precedence over the suffix-based value.

The wallet is of type `SINGLE`.
Use the `walletType` property to configure different types.
See other valid options at https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/datatypes/GenerateAutonomousDatabaseWalletDetails[].

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db.html[Access an Oracle Autonomous Database] to learn more.
