Oracle Cloud Autonomous Database connection information and credentials are stored in the https://docs.oracle.com/en-us/iaas/Content/Database/Tasks/adbconnecting.htm[Oracle Wallet].

Micronaut can automatically generate and download the Wallet and configure the data source.

First you must configure the <<authentication, authentication provider>>.

Then simply add a dependency to one of the Micronaut connection pool implementation.

NOTE: Automated configuration is currently supported only for the HikariCP and UCP connection pool.

dependency:micronaut-jdbc-ucp[groupId="io.micronaut.sql", scope="runtime"]

dependency:micronaut-jdbc-hikari[groupId="io.micronaut.sql", scope="runtime"]

To use automated data source configuration from the Wallet, provide a configuration similar to the following:
[source,yaml]
.application.yaml
----
datasources:
  default:
    ocid: ocid1.autonomousdatabase.oc1..... // <1>
    serviceAlias: foo_medium // <2>
    walletPassword: micronaut.1 // <3>
----
<1> database ocid
<2> service alias name, generally in format `<dbname>_[high|medium|low]`
<3> password to encrypt the keys inside the wallet, that  must be at least 8 characters long and must include at least 1 letter and either 1 numeric character or 1 special character

By default the wallet is of type `SINGLE`. Use `walletType` option to configure different type. See other valid options at https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/datatypes/GenerateAutonomousDatabaseWalletDetails[].