Oracle Cloud Autonomous Database connection information and credentials are stored in the https://docs.oracle.com/en-us/iaas/Content/Database/Tasks/adbconnecting.htm[Oracle Wallet].

Micronaut can automatically generate and download the Wallet and configure the data source.

First you need the correct version of the Oracle Database driver and required modules. To ensure you are using the right version apply the 21.1.0.0 or above Oracle Database BOM with Gradle:

[source,groovy]
----
implementation platform("com.oracle.database.jdbc:ojdbc-bom:21.1.0.0")
----

Or with Maven:

[source,xml]
----
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.oracle.database.jdbc</groupId>
        <artifactId>ojdbc-bom</artifactId>
        <version>21.1.0.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
----

Secondly you need to add a dependency on the `micronaut-oraclecloud-atp` module:

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-atp[scope="runtime"]

Then you must configure the <<authentication, authentication provider>>.

Then simply add a dependency to one of the Micronaut connection pool implementations.

NOTE: Automated configuration is currently supported only for the HikariCP and UCP connection pool.

dependency:micronaut-jdbc-ucp[groupId="io.micronaut.sql", scope="runtime"]

Or:

dependency:micronaut-jdbc-hikari[groupId="io.micronaut.sql", scope="runtime"]

NOTE: Note that `micronaut-oraclecloud-atp` module is compatible with Java 11+.

To use automated data source configuration from the Wallet, provide a configuration similar to the following:
[source,yaml]
.application.yaml
----
datasources:
  default:
    ocid: ocid1.autonomousdatabase.oc1..... // <1>
    walletPassword: micronaut.1 // <2>
    username: foo // <3>
    password: bar // <4>
----
<1> autonomous database id
<2> password to encrypt the keys inside the wallet; must be at least eight characters long and must include at least one letter and either one numeric character or one special character
<3> database username
<4> database password

NOTE: The `username` and `password` are not automatically generated and must be created in advance.

Module uses `<db_name>_high` as a default service alias. This can be overriden with the `serviceAlias` property.

The wallet is of type `SINGLE`. Use the `walletType` property to configure different types. See other valid options at https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/datatypes/GenerateAutonomousDatabaseWalletDetails[].
