Oracle Functions are based on https://fnproject.io/[Project.fn]. You can write simple functions targeting the Oracle Function environment by extending from the api:oci.function.OciFunction[] superclass.

NOTE: Micronaut's Oracle Function support can utilize GraalVM `native-image` running within a Docker container. This will result in extremely responsive serverless functions utilizing very few Cloud resources.

This superclass enables dependency injection for the function. Note that the the function definition must conform to the following rules:

* The class must have a public no arguments constructor
* A public method that executes the function must be defined
* The class must be annotated with `@Singleton`

Micronaut support for Oracle Functions can be combined with the OCI SDK support to give your serverless functions access to the OCI SDKs as needed.

NOTE: You must have <<resource-principals, resource principal authentication>> properly configured in order for this example to work.

With Micronaut 2.1 and above you can create a new Oracle Function with the following command line command:

[source,bash]
----
$ mn create-function-app myfunction --features oracle-function
----

This will create a Gradle build that sets up the Micronaut Gradle plugin. The only changes you need to make are to modify the `build.gradle` and alter the `dockerBuild` and `dockerBuildNative` to point at the Oracle Cloud Registry you wish the publish the docker images for the function:

[source,bash]
----
dockerBuild {
    images = ["[REGION].ocir.io/[TENANCY_ID]/[REPOSITORY]/$project.name:$project.version"]
}

dockerBuildNative {
    images = ["[REGION].ocir.io/[TENANCY_ID]/[REPOSITORY]/$project.name:$project.version"]
}
----

The `REGION` should be altered to your region, the `TENANCY_ID` to your tenancy and the `REPOSITORY` to the Docker repository you wish to publish to.

[#functions-build]
=== Build

The following provides a serverless function example that uses the Object Storage API to list the available buckets:

snippet::example.ListBucketsFunction[project-base="docs-examples/example-function", source="main", tags="imports,class"]

<1> A public class with a no argument constructor annotated with `@Singleton` and extending from api:oci.function.OciFunction[]
<2> You can use the `@Inject` annotation to inject SDK components

Once you have defined the function, define a public method that is the function handler, for example:

snippet::example.ListBucketsFunction[project-base="docs-examples/example-function", source="main", tags="method", indent="0"]

The above example uses the Object Storage API to list the available buckets.

[#functions-dockerfile]
=== Docker Build

To build the Oracle Function, run the `./gradlew dockerBuild` command or to build the GraalVM native image version run `./gradlew dockerBuildNative`.

[#functions-deploy]
=== Deploy

To deploy the Oracle Function as a Java function, run `./gradlew dockerPush` to push the function to Oracle Container Registry, or to deploy the GraalVM native image version run `./gradlew dockerPushNative`.

Note that these commands only publish the function to Oracle Container Registry. To make the function invokable, use the Oracle Cloud UI to create the function, or use the `fn` command line application to create the function from the container image:

.Creating a Function from a Container Image
[source,bash]
----
$ fn create function myapp myfunction [REGION].ocir.io/[TENANCY]/[REPOSITORY/[FUNCTION_NAME]:[FUNCTION_VERSION]

## For example:
$ fn create function myapp myfunction us-ashburn-1.ocir.io/mytenancy/myrepository/myfunction:1.0.0
----

NOTE: For Java functions that do not use Native Image you will need to pass `--memory 512 --timeout 120` as Java functions occupy more memory that native functions.

If you publish a new image using `./gradlew dockerPush` or `./gradlew dockerPushNative` for an existing function you can also update it with `fn update`:

.Updating an existing Function from a Container Image
[source,bash]
----
$ fn update function myapp myfunction [REGION].ocir.io/[TENANCY]/[REPOSITORY/[FUNCTION_NAME]:[FUNCTION_VERSION]
----
