Oracle Functions are based on https://fnproject.io/[Project.fn].
You can write simple functions targeting the Oracle Function environment by extending the api:oci.function.OciFunction[] superclass.

NOTE: Micronaut's Oracle Function support can use GraalVM `native-image` running within a Docker container.
This will result in extremely responsive serverless functions using very few Cloud resources.

This superclass enables dependency injection for the function.
Note that the function class must conform to the following rules:

* it must have a public, no-arguments constructor
* it must have a public method that executes the function
* it must be annotated with `@Singleton`

Micronaut support for Oracle Functions can be combined with the OCI SDK support to give your serverless functions access to the OCI SDKs as needed.

NOTE: You must have <<resource-principals, resource principal authentication>> properly configured in order for this example to work.

=== Creating a Function with a Gradle build

You can create a new Oracle Function using Gradle as the build tool with the following:

[source,bash]
----
$ mn create-function-app myfunction --features oracle-function
----

This will create a Micronaut project with a Gradle build that configures the Micronaut Gradle plugin.
The only necessary changes are to modify `build.gradle` and alter the `dockerBuild` and `dockerBuildNative` sections to specify the Oracle Cloud Registry to publish the docker images to for the function:

[source,bash]
----
dockerBuild {
    images = ["[REGION].ocir.io/[TENANCY_ID]/[REPOSITORY]/$project.name:$project.version"]
}

dockerBuildNative {
    images = ["[REGION].ocir.io/[TENANCY_ID]/[REPOSITORY]/$project.name:$project.version"]
}
----

Change the `REGION` to your region, the `TENANCY_ID` to your tenancy and the `REPOSITORY` to your Docker repository.

=== Creating a Function with a Maven build

You can create a new Oracle Function using Maven as the build tool with the following:

[source,bash]
----
$ mn create-function-app myfunction --build=maven --features oracle-function
----

This will create a Micronaut project with a Maven build that configures the Micronaut Maven plugin.
The only necessary changes are to modify `pom.xml` and add these properties in the `<properties>` section to specify the Oracle Cloud Registry to publish the docker images to for the function

[source, xml]
----
<jib.docker.image>[REGION].ocir.io/[TENANCY_ID]/[REPOSITORY]/${project.artifactId}</jib.docker.image>

<jib.docker.tag>${project.version}</jib.docker.tag>
----

Change the `REGION` to your region, the `TENANCY_ID` to your tenancy and the `REPOSITORY` to your Docker repository.

Also add a property to specify the full class name and package of the function class, e.g.

[source, xml]
----
<exec.mainClass>com.mycompany.MyFunction</exec.mainClass>
----

[#functions-build]
=== Build

The following provides a serverless function example that uses the Object Storage API to list the available buckets:

snippet::example.ListBucketsFunction[project-base="docs-examples/example-function", source="main", tags="imports,class"]

<1> A public class with a no argument constructor annotated with `@Singleton` and extending from api:oci.function.OciFunction[]
<2> You can use the `@Inject` annotation to inject SDK components

Once you have defined the function, define a public method to be the function handler, e.g.:

snippet::example.ListBucketsFunction[project-base="docs-examples/example-function", source="main", tags="method", indent="0"]

The above example uses the Object Storage API to list the available buckets.

[#functions-dockerfile]
=== Docker Build

To build the Oracle Function with Gradle, run the `./gradlew dockerBuild` command, or build a GraalVM native executable by running `./gradlew dockerBuildNative`.

To build the Oracle Function with Maven, run the `./mvnw package -Dpackaging=docker` command, or build a GraalVM native executable by running `./mvnw package -Dpackaging=docker-native`.

[#functions-deploy]
=== Deploy

To deploy the Oracle Function as a Java function with Gradle, run `./gradlew dockerPush` to push the function to Oracle Container Registry, or deploy the GraalVM native executable by running `./gradlew dockerPushNative`.

To deploy the Oracle Function as a Java function with Maven, run `./mvnw deploy -Dpackaging=docker` to push the function to Oracle Container Registry, or deploy the GraalVM native executable by running `./mvnw deploy -Dpackaging=docker-native`.

Note that these commands only publish the function to Oracle Container Registry.
To make the function invokable, use the Oracle Cloud UI to create the function, or use the `fn` command line application to create the function from the container image:

.Creating a Function from a Container Image
[source,bash]
----
$ fn create function myapp myfunction [REGION].ocir.io/[TENANCY]/[REPOSITORY/[FUNCTION_NAME]:[FUNCTION_VERSION]

## For example:
$ fn create function myapp myfunction us-ashburn-1.ocir.io/mytenancy/myrepository/myfunction:1.0.0
----

NOTE: For Java functions that do not use Native Image you will need to pass `--memory 512 --timeout 120` as Java functions use more memory that native functions.

If you publish a new image using `./gradlew dockerPush` or `./gradlew dockerPushNative` (or with Maven using `./mvnw deploy -Dpackaging=docker` or `./mvnw deploy -Dpackaging=docker-native`) for an existing function you can also update it with `fn update`:

.Updating an existing Function from a Container Image
[source,bash]
----
$ fn update function myapp myfunction [REGION].ocir.io/[TENANCY]/[REPOSITORY/[FUNCTION_NAME]:[FUNCTION_VERSION]
----

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-oracle-function.html[Deploy a Micronaut Function (Serverless) Application to Oracle Cloud] to learn more.
