Oracle Functions are based on https://fnproject.io/[Project.fn]. You can write simple functions targeting the Oracle Function environment by extending from the api:oci.function.OciFunction[] super class.

NOTE: Micronaut's Oracle Function support can utilize GraalVM `native-image` running within a Docker container. This will result in extremely responsive serverless functions utilizing very few Cloud resources.

This super class enables dependency injection for the function. Note that the the function definition must conform to the following rules:

* The class must have a public no arguments constructor
* A public method that executes the function must be defined
* The class must be annotated with `@Singleton`

Micronaut support for Oracle Functions can be combined with the OCI SDK support to give your serverless functions accesss to the OCI SDKs as needed.

NOTE: You must have <<resource-principals, resource principal authentication>> properly configured in order for this example to work.

=== Dependencies

To get started with Gradle as a build tool you should add the Project.fn repository and the Micronaut Gradle plugin:

[source,groovy]
----
plugins {
    id "io.micronaut.application", version "1.0.0.M9"
}

repositories {
    maven {
        url("https://dl.bintray.com/fnproject/fnproject")
    }
}
----

And include a runtime dependency on Project.fn:

dependency:com.fnproject.fn:runtime[version="1.0.109",scope="runtimeOnly"]

Oracle Function support requires the Micronaut OCI Functions module:

dependency:io.micronaut.oci:micronaut-oci-function[version={ociVersion}]

Optionally, to use the OCI SDK module from within your function, include the `micronaut-oci-sdk`:

dependency:io.micronaut.oci:micronaut-oci-sdk[]

In addition, your function will need the necessary OCI SDK dependency/dependencies. For example, the object storage module:

dependency:com.oracle.oci.sdk:oci-java-sdk-objectstorage[version={ociVersion}]

[#functions-build]
=== Build


The following provides a serverless function example that uses the Object Storage API to list the available buckets:

snippet::example.ListBucketsFunction[project-base="docs-examples/example-function", source="main", tags="imports,class"]

<1> A public class with a no argument constructor annotated with `@Singleton` and extending from api:oci.function.OciFunction[]
<2> You can use the `@Inject` annotation to inject SDK components

Once you have defined the function you should define a public method that is the function handler. For example:

snippet::example.ListBucketsFunction[project-base="docs-examples/example-function", source="main", tags="method", indent="0"]

The above example uses the Object Storage API to list the available buckets.

[#functions-dockerfile]
=== Dockerfile

To build a Oracle Cloud Function into a GraalVM `native-image` plugin, you will need to include the following `Dockerfile` in your function's root directory.

[source,Dockerfile]
----
include::docs-examples/example-function-java/Dockerfile[tags=dockerfile]
----

[#functions-deploy]
=== Deploy

To deploy your function, first use `./gradlew buildLayers` to build the necessary artifacts that the `Dockerfile` needs to generate the `native-image`. Then deploy per the normal Oracle Functions method (IE: `fn deploy --app [your app name]`).

WARNING: Deploying your function with Micronaut will take longer than deploying without because of the `native-image` support. Runtime performance will greatly make up for the slow deployment.
