This module provides a Netty client implementation for the Java OCI SDK. The client uses link:https://micronaut-projects.github.io/micronaut-serialization/latest/guide/[Micronaut Serialization].

Add a dependency to the `micronaut-oraclecloud-httpclient-netty` module:

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-httpclient-netty[]

For serialization to work correctly, use one of the micronaut OCI SDK modules instead of the OCI SDK modules. For example, for Object Store define the dependency:

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-bmc-objectstorage[]

### Importing SDK's not compiled with Micronaut

If an OCI SDK client exists that is built with OCI SDK v3 or above but not compiled with Micronaut and therefore missing the the required Micronaut Serialization types you can import the sdk use the `@SdkImport` annotation.

First you should add an annotation processor dependency:

dependency:io.micronaut.oraclecloud:oraclecloud-serde-processor[scope="annotationProcessor"]

Then declare `@SdkImport` on any class passing the type of the client you wish to import. For example:

.Declaring `@SdkImport`
[source,java]
----
@SdkImport(DisasterRecoveryClient.class)
----

### Migrate

Replace the `com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey` with the `micronaut-oraclecloud-httpclient-netty` client and the `com.oracle.oci.sdk:oci-java-sdk-bom` with `micronaut-oraclecloud-bom`.

Then replace other OCI SDK modules with micronaut ones. To simplify the process, you can utilize the following regular expression:

For Maven replace
[source,regex]
----
<dependency>(\s*)<groupId>com.oracle.oci.sdk</groupId>(\s*)<artifactId>oci-java-sdk-([^<]+)</artifactId>(((?!</dependency>)[\s\S])+)</dependency>
----
with
[source,regex]
----
<dependency>$1<groupId>io.micronaut.oraclecloud</groupId>$2<artifactId>micronaut-oraclecloud-bmc-$3</artifactId>$4</dependency>
----

For Gradle replace
[source,regex]
----
com.oracle.oci.sdk:oci-java-sdk-([^:"')]+)
----
with
[source,regex]
----
io.micronaut.oraclecloud:micronaut-oraclecloud-bmc-$1
----

If you plan to use the modules in a Micronaut application, add one of the `micronaut-oraclecloud-sdk`, `micronaut-oraclecloud-sdk-rxjava2` or `micronaut-oraclecloud-sdk-reactor` modules.

### Configuration

The jersey HTTP client can be configured through a `ClientConfigurator` and `StandardClientProperties`. Only some of these properties are supported for the netty client. Which properties are supported also depends on whether the netty client is used in a managed context, i.e. whether the SDK client is injected from an application context. The following properties are supported:

- `StandardClientProperties.BUFFER_REQUEST` always supported
- `StandardClientProperties.READ_TIMEOUT` supported only when the client is _not_ managed
- `StandardClientProperties.CONNECT_TIMEOUT` supported only when the client is _not_ managed
- `StandardClientProperties.ASYNC_POOL_SIZE` supported only when the client is _not_ managed

Other properties — particularly those related to proxies and TLS configuration — are not supported directly.
Instead, these settings should be configured using the standard Micronaut HTTP client configuration properties, with a special service name prefix.
For example, to configure the managed Netty client, you can use properties like `oci.client.read-timeout`. This allows you to configure TLS, proxy settings, timeouts, connection pool sizes, and other HTTP client options.

Similarly, you can configure other Micronaut-provided clients by specifying the appropriate service ID. For example:

- `oci.clients.objectstorage.read-timeout` for the Object Storage client

- `oci.clients.identity.read-timeout` for the Identity client

You can find a client’s service ID by checking the factory class that creates it or directly by client name. For example:

- IdentityClientFactory produces IdentityClient → identity.
- ObjectStorageClientFactory produces ObjectStorageClient → objectstorage.

NOTE: You should choose either `micronaut.http.services.oci` or `oci.client` to configure your oci client. If you supply both you will get `NonUniqueBeanException`.

#### Logging

To enable logging of all requests, set the `micronaut.http.services.oci.log-level` or `oci.client.log-level` property to `INFO`. Log messages
will appear at `INFO` level.

WARNING: This logging includes sensitive data such as authentication tokens, and should only be enabled for debugging
purposes.
