This module provides a netty client implementation for the Java OCI SDK. The client uses link:https://micronaut-projects.github.io/micronaut-serialization/latest/guide/[Micronaut Serialization].

Add a dependency to the `micronaut-oraclecloud-httpclient-netty` module:

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-httpclient-netty[]

For serialization to work correctly, use one of the micronaut OCI SDK modules instead of the OCI SDK modules. For example, for Object Store define the dependency:

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-bmc-objectstorage[]

### Migrate

Replace the `com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey` with the `micronaut-oraclecloud-httpclient-netty` client and the `com.oracle.oci.sdk:oci-java-sdk-bom` with `micronaut-oraclecloud-bom`.

Then replace other OCI SDK modules with micronaut ones. To simplify the process, you can utilize the following regular expression:

For Maven replace
[source,regex]
----
<dependency>(\s*)<groupId>com.oracle.oci.sdk</groupId>(\s*)<artifactId>oci-java-sdk-([^<]+)</artifactId>(((?!</dependency>)[\s\S])+)</dependency>
----
with
[source,regex]
----
<dependency>$1<groupId>io.micronaut.oraclecloud</groupId>$2<artifactId>micronaut-oraclecloud-bmc-$3</artifactId>$4</dependency>
----

For Gradle replace
[source,regex]
----
com.oracle.oci.sdk:oci-java-sdk-([^:"')]+)
----
with
[source,regex]
----
io.micronaut.oraclecloud:micronaut-oraclecloud-bmc-$1
----

If you plan to use the modules in a Micronaut application, add one of the `micronaut-oraclecloud-sdk`, `micronaut-oraclecloud-sdk-rxjava2` or `micronaut-oraclecloud-sdk-reactor` modules.

### Configuration

The jersey HTTP client can be configured through a `ClientConfigurator` and `StandardClientProperties`. Only some of these properties are supported for the netty client. Which properties are supported also depends on whether the netty client is used in a managed context, i.e. whether the SDK client is injected from an application context. The following properties are supported:

- `StandardClientProperties.BUFFER_REQUEST` always supported
- `StandardClientProperties.READ_TIMEOUT` supported only when the client is _not_ managed
- `StandardClientProperties.CONNECT_TIMEOUT` supported only when the client is _not_ managed
- `StandardClientProperties.ASYNC_POOL_SIZE` supported only when the client is _not_ managed

All other properties, in particular those related to proxies or TLS configuration, are not supported. Instead, you can configure these settings through the normal Micronaut HTTP client configuration properties, with the special service name `oci`, for example the `micronaut.http.services.oci.read-timeout` property. For the managed netty client, this allows you to configure TLS, proxy settings, various timeouts and the pool size.
