The https://docs.oracle.com/en-us/iaas/Content/Monitoring/Concepts/monitoringoverview.htm[OCI Monitoring service] enables you to actively and passively monitor your cloud resources using the Metrics and Alarms features.

The `micronaut-oraclecloud-micrometer` module integrates https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/[Micronaut's Micrometer support] with the OCI Monitoring service.

To begin, add the standard dependencies for the Micronaut Micrometer module per the https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/#_configuration[documentation].

Next, add a dependency on the `micronaut-oraclecloud-micrometer` module:

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-micrometer[scope="runtime"]

Also add a dependency for the OCI SDK Monitoring module:

dependency:com.oracle.oci.sdk:oci-java-sdk-monitoring[scope="implementation"]

Then configure the <<authentication, authentication provider>>.

You can configure this Micrometer reporter using `micronaut.metrics.export.oraclecloud`.
The most commonly changed configuration properties are listed below:

|=======
|*Name* |*Description*
|enabled | Whether to enable the reporter, e.g., set to `false` when running locally. Default: `true`.
|application-name | Application name used as a common dimension. Default: `${micronaut.application.name}`.
|namespace | Metrics namespace. Required.
|resource-group | Metrics resource group.
|compartment-id | Oracle Cloud compartment OCID. Default: the Oracle SDK tenantId.
|step |How frequently to report metrics. Default: `PT1M` (1 min).  See `java.time.Duration#parse(CharSequence)`.
|batch-size |How many metrics to send per batch. Default: `50` (Max allowed number of metrics for current API).
|descriptions | Whether to send meter descriptions to InfluxDB. Disable to minimize the amount of data sent on each scrape. Default: `true`
|=======

.Example Oracle Cloud Config
[configuration]
----
micronaut:
  metrics:
    enabled: true
    export:
      oraclecloud:
        enabled: true
        namespace: test
        resourceGroup: foo
----

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-metrics-oci.html[Collect Metrics with the Micronaut Framework and Monitor them on Oracle Cloud] to learn more.

=== OCI SDK client metrics

If you are using OCI SDK clients instrumented by Micronaut, by default metrics will be collected for each request.

|=======
|*Name* |*Type* |*Description*
|micronaut.metrics.oci.sdk.client.enabled | boolean |Whether to enable the OCI SDK client metrics. Default: `true`.
|=======
