The following modules are provided.

=== micronaut-oraclecloud-common

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-common[]

Provides the common functionality and sets up the following beans:

* link:{ocidocs}/com/oracle/bmc/auth/BasicAuthenticationDetailsProvider.html[BasicAuthenticationDetailsProvider] - Authentication details auto-detected from local `$USER/.oci/config` or environment
* link:{ocidocs}/com/oracle/bmc/ClientConfiguration.html[ClientConfiguration] - Common configuration for all clients
* api:oci.core.TenancyIdProvider[] - Interface to resolve current tenancy

=== micronaut-oraclecloud-httpclient-netty

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-httpclient-netty[]

Provides an implementation of the OCI SDK client based on Netty and Micronaut Serialization.

NOTE: `micronaut-oraclecloud-bmc-[OCI SDK Client]` modules must be used instead of the OCI Java SDK modules, as they are compatible with this client.

=== micronaut-oraclecloud-bmc-[OCI SDK Client]

OCI SDK client dependencies compatible with the `micronaut-oraclecloud-httpclient-netty`.
The modules also support injection of the OCI SDK client interfaces.
Injection of Reactor or RxJava 2 clients is supported with the addition of one of the following dependencies:

dependency:io.micronaut.reactor:micronaut-reactor[]
dependency:io.micronaut.rxjava2:micronaut-rxjava2[]

=== micronaut-oraclecloud-sdk

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-sdk[]

Provides support for injecting any of the available SDK client interfaces.

NOTE: The module is only required when you want to use the OCI SDK clients with a Jersey implementation, as the
Netty client implementations support Micronaut injection by default. For example to use Object Vault with
OCI Jersey client you would define a dependency on this module as well as:

dependency:com.oracle.oci.sdk:oci-java-sdk-vault[]
dependency:com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey[]


=== micronaut-oraclecloud-sdk-rxjava2

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-sdk-rxjava2[]

Provides support for injecting inject RxJava 2 client implementations.

NOTE: The module is only required when you want to use the OCI SDK clients with a Jersey implementation, as the
Netty client implementations support Micronaut injection by default. For example to use Object Vault with
OCI Jersey client you would define a dependency on this module as well as:

dependency:com.oracle.oci.sdk:oci-java-sdk-vault[]
dependency:com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey[]

=== micronaut-oraclecloud-sdk-reactor

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-sdk-reactor[]

Provides support for injecting inject Reactor client implementations.

NOTE: The module is only required when you want to use the OCI SDK clients with a Jersey implementation, as the
Netty client implementations support Micronaut injection by default. For example to use Object Vault with
OCI Jersey client you would define a dependency on this module as well as:

dependency:com.oracle.oci.sdk:oci-java-sdk-vault[]
dependency:com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey[]


=== micronaut-oraclecloud-function

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-function[]

Provides the api:oci.function.OciFunction[] superclass that you can subclass to write Oracle Cloud Functions in Micronaut that can utilize Micronaut dependency injection.

=== micronaut-oraclecloud-function-http

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-function-http[]

Provides the api:oci.function.http.HttpFunction[] class that can be used as a handler to write HTTP API Gateway function handlers that delegate to regular Micronaut controllers.

=== micronaut-oraclecloud-atp

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-atp[]

Provides support for configuring the data source connection for the UCP and HikariCP connection pools by specifying Oracle Cloud Autonomous Database configuration.

NOTE: The module generates the OracleWallet on startup.

=== micronaut-oraclecloud-micrometer

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-micrometer[]

Provides support for sending https://micrometer.io[Micrometer] metrics to the https://docs.oracle.com/en-us/iaas/Content/Monitoring/Concepts/monitoringoverview.htm[Oracle Cloud Monitoring] service.

=== micronaut-oraclecloud-vault

dependency:io.micronaut.oraclecloud:micronaut-oraclecloud-vault[]

Provides support for https://docs.micronaut.io/latest/guide/#cloudConfiguration[Distributed Configuration] with https://docs.oracle.com/en-us/iaas/Content/KeyManagement/Concepts/keyoverview.htm[Oracle Cloud Vault] service.
