The following modules are provided.

=== micronaut-oraclecloud-common

dependency:io.micronaut.oci:micronaut-oraclecloud-common[version={version}]

Provides the common functionality and sets up the following beans:

* link:{ocidocs}/com/oracle/bmc/auth/BasicAuthenticationDetailsProvider.html[BasicAuthenticationDetailsProvider] - Authentication details auto-detected from local `$USER/.oci/config` or environment
* link:{ocidocs}/com/oracle/bmc/ClientConfiguration.html[ClientConfiguration] - Common configuration for all clients
* api:oci.core.TenancyIdProvider[] - Interface to resolve current tenancy

=== micronaut-oraclecloud-sdk

dependency:io.micronaut.oci:micronaut-oraclecloud-sdk[version={ociVersion}]

Provides support for injecting any of the available SDK client interfaces.

NOTE: This module does not have a dependency on any one module. You should add these to your project as needed. For example to use Object Storage you would define a dependency on this module as well as:

dependency:com.oracle.oci.sdk:oraclecloud-java-sdk-objectstorage[]

=== micronaut-oraclecloud-function

dependency:io.micronaut.oci:micronaut-oraclecloud-function[version={ociVersion}]

Provides the api:oci.function.OciFunction[] super class that you can subclass to enable the ability to write Oracle Cloud Functions in Micronaut that can utilize Micronaut dependency injection services.

=== micronaut-oraclecloud-function-http

dependency:io.micronaut.oci:micronaut-oraclecloud-function-http[version={ociVersion}]

Provides the api:oci.function.http.HttpFunction[] class that can be used as a handler to write HTTP API Gateway function handlers that delegate to regular Micronaut controllers.