plugins {
    id 'io.micronaut.build.internal.oraclecloud-example-httpfunction'
    id 'io.micronaut.build.internal.oraclecloud-python-example'
}

tasks.withType(Test).configureEach {
    // Every function invocation of the tests starts a GraalPy runtime in a new Fn classloader
    maxHeapSize = '3g'
}
