plugins {
    id 'io.micronaut.build.internal.common'
    id 'io.micronaut.build.internal.oraclecloud-base'
}

dependencies {
    annotationProcessor(mn.micronaut.inject.java)
    api(mn.micronaut.inject)
    testImplementation(mnSql.micronaut.jdbc.ucp)
    testImplementation(mnTest.micronaut.test.spock)
    testImplementation(projects.micronautOraclecloudAtp)
    testRuntimeOnly(mnSql.h2)
}
