[versions]
micronaut = "4.10.0"
micronaut-platform = "4.9.1"
micronaut-docs = "2.0.0"
fn = '1.0.209'
graal-svm = "23.1.7"
javapoet = '1.13.0'
kotlin = '1.9.25'
logback-json-classic = '0.1.5'
slf4j-jcl = '2.0.17'
shadow = '8.0.0'
groovy = "4.0.28"
spock = "2.3-groovy-4.0"
oci = "3.72.1"
oracle-database-security = "21.17.0.0"
protobuf = '0.9.5'

managed-apache-http-core5 = "5.3.4"
micronaut-gradle-plugin = "4.5.4"
micronaut-groovy = "4.7.0"
micronaut-kotlin = "4.7.0"
micronaut-kubernetes = "7.1.1"
micronaut-micrometer = "5.12.0"
micronaut-security = "4.13.1"
micronaut-reactor = "3.8.0"
micronaut-rxjava2 = "2.8.0"
micronaut-serde = "2.15.1"
micronaut-servlet = "5.4.0"
micronaut-sourcegen = "1.8.2"
micronaut-sql = "6.2.1"
micronaut-test = "4.8.1"
micronaut-logging = "1.7.1"
micronaut-validation = "4.10.0"
micronaut-discovery-client = "4.7.1"
sonatype-scan = "3.0.0"

#TODO remove these versions once dependencies do not bring vulnerable versions of these libraries
#https://ossindex.sonatype.org/vulnerability/CVE-2025-48924?component-type=maven&component-name=org.apache.commons%2Fcommons-lang3
commons-lang3 = "3.18.0"
#https://ossindex.sonatype.org/vulnerability/CVE-2025-53864?component-type=maven&component-name=com.google.code.gson%2Fgson
gson = "2.12.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

# micronaut boms
micronaut-groovy = { module = "io.micronaut.groovy:micronaut-groovy-bom", version.ref = "micronaut-groovy" }
micronaut-kotlin = { module = "io.micronaut.kotlin:micronaut-kotlin-bom", version.ref = "micronaut-kotlin" }
micronaut-kubernetes = { module = "io.micronaut.kubernetes:micronaut-kubernetes-bom", version.ref = "micronaut-kubernetes" }
micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-security = { module = "io.micronaut.security:micronaut-security-bom", version.ref = "micronaut-security" }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
micronaut-rxjava2 = { module = "io.micronaut.rxjava2:micronaut-rxjava2-bom", version.ref = "micronaut-rxjava2" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-servlet = { module = "io.micronaut.servlet:micronaut-servlet-bom", version.ref = "micronaut-servlet" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }
micronaut-sourcegen = { module = "io.micronaut.sourcegen:micronaut-sourcegen-bom", version.ref = "micronaut-sourcegen" }
micronaut-docs = { module = "io.micronaut.docs:micronaut-docs-asciidoc-config-props", version.ref = "micronaut-docs" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-discovery-client = { module = "io.micronaut.discovery:micronaut-discovery-client-bom", version.ref = "micronaut-discovery-client" }
micronaut-test = { module = "io.micronaut.test:micronaut-test-bom", version.ref = "micronaut-test" }
micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }

fn-api = { module = 'com.fnproject.fn:api', version.ref = 'fn' }
fn-runtime = { module = 'com.fnproject.fn:runtime', version.ref = 'fn' }
fn-testing-junit4 = { module = 'com.fnproject.fn:testing-junit4', version.ref = 'fn' }
graal-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graal-svm"}
javapoet = { module = 'com.squareup:javapoet', version.ref = 'javapoet' }
junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter-engine', version = '' }
junit-platform-engine = { module = "org.junit.platform:junit-platform-suite-engine" }
kotlin-reflect = { module = 'org.jetbrains.kotlin:kotlin-reflect', version.ref = 'kotlin' }
kotlin-stdlib = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8', version.ref = 'kotlin' }
logback-json-classic = { module = 'ch.qos.logback.contrib:logback-json-classic', version.ref = 'logback-json-classic' }
slf4j-jcl = { module = 'org.slf4j:jcl-over-slf4j', version.ref = 'slf4j-jcl' }
commons-lang3 = { module = 'org.apache.commons:commons-lang3', version.ref = 'commons-lang3' }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
oci-bom = { module = "com.oracle.oci.sdk:oci-java-sdk-bom", version.ref = "oci" }
oci-common = { module = 'com.oracle.oci.sdk:oci-java-sdk-common', version.ref = "oci" }
oci-common-httpclient = { module = 'com.oracle.oci.sdk:oci-java-sdk-common-httpclient', version.ref = "oci" }
oci-common-httpclient-jersey3 = { module = 'com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey3', version.ref = "oci" }
oci-objectstorage = { module = 'com.oracle.oci.sdk:oci-java-sdk-objectstorage', version.ref = "oci" }
oci-disasterrecovery = { module = 'com.oracle.oci.sdk:oci-java-sdk-disasterrecovery', version.ref = "oci" }
oci-encryption = { module = 'com.oracle.oci.sdk:oci-java-sdk-encryption', version.ref = "oci" }
oci-oke-workload-identity = { module = 'com.oracle.oci.sdk:oci-java-sdk-addons-oke-workload-identity', version.ref = "oci" }
oci-graalvm = { module = 'com.oracle.oci.sdk:oci-java-sdk-addons-graalvm', version.ref = "oci" }
oracle-security-oraclepki = { module = 'com.oracle.database.security:oraclepki' }
oracle-jdbc-bom = { module = "com.oracle.database.jdbc:ojdbc-bom" }
oracle-security-cert = { module = "com.oracle.database.security:osdt_cert", version.ref = "oracle-database-security" }
oracle-security-core = { module = "com.oracle.database.security:osdt_core", version.ref = "oracle-database-security" }
oracle-xml-xdb = { module = 'com.oracle.database.xml:xdb' }
apache-http-core5 = { module = 'org.apache.httpcomponents.core5:httpcore5', version.ref = 'managed-apache-http-core5' }

#plugins
kotlin-gradle-plugin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }
kotlin-gradle-allopen = { module = 'org.jetbrains.kotlin:kotlin-allopen', version.ref = 'kotlin' }
shadow-plugin = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "shadow" }
micronaut-gradle-plugin = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref="micronaut-gradle-plugin" }
protobuf-gradle-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobuf" }
sonatype-scan = { module = "org.sonatype.gradle.plugins:scan-gradle-plugin", version.ref = "sonatype-scan" }

#dummy dependencies for renovate
groovy = { module = "org.apache.groovy:groovy-bom", version.ref = "groovy" }
spock = { module = "org.spockframework:spock-bom", version.ref = "spock" }
