/*
 * Copyright 2017-2020 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Package containing client factories for the Oracle Cloud SDK.
 */
// Implementation Note: Client bean definition factories are generated by
// the oci-sdk-processor subproject and OracleCloudSdkProcessor
@Requires(classes = {
        BdsClient.class,
        BdsAsyncClient.class,
        BudgetClient.class,
        BudgetAsyncClient.class,
        ObjectStorageClient.class,
        ObjectStorageAsyncClient.class,
        FileStorageClient.class,
        FileStorageAsyncClient.class,
        GatewayClient.class,
        GatewayAsyncClient.class
})
package io.micronaut.oci.clients;

import com.oracle.bmc.apigateway.GatewayAsyncClient;
import com.oracle.bmc.apigateway.GatewayClient;
import com.oracle.bmc.bds.BdsAsyncClient;
import com.oracle.bmc.bds.BdsClient;
import com.oracle.bmc.budget.BudgetAsyncClient;
import com.oracle.bmc.budget.BudgetClient;
import com.oracle.bmc.filestorage.FileStorageAsyncClient;
import com.oracle.bmc.filestorage.FileStorageClient;
import com.oracle.bmc.objectstorage.ObjectStorageAsyncClient;
import com.oracle.bmc.objectstorage.ObjectStorageClient;
import io.micronaut.context.annotation.Requires;
