plugins {
    id 'io.micronaut.build.internal.oraclecloud-native-tests'
}

application {
    mainClass = "helloworld.Application"
}

// ensure Jackson databind is not on the classpath for tests
configurations.configureEach {
    exclude(group: "com.fasterxml.jackson.core", module: "jackson-databind")
}

dependencies {
    implementation(mn.micronaut.context)
    implementation(mn.micronaut.management)
    implementation(mn.reactor)
    implementation(mnMicrometer.micrometer.core)
    implementation(mnMicrometer.micronaut.micrometer.core)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mnSql.micronaut.jdbc.hikari)
    implementation(platform(libs.oci.bom))
    implementation(projects.micronautOraclecloudAtp)
    implementation(projects.micronautOraclecloudMicrometer)
    implementation(projects.micronautOraclecloudSdk)
    implementation(projects.micronautOraclecloudVault)
    runtimeOnly(mnLogging.logback.classic)
}
