plugins {
    id 'io.micronaut.build.internal.oraclecloud-module'
}

dependencies {
    api(projects.micronautOraclecloudBmcCertificates)
    compileOnly(mn.micronaut.http.client)
    implementation(mn.micronaut.http.server.netty)
    implementation(mn.micronaut.inject.java)
    implementation(mn.micronaut.retry)
    implementation(mnReactor.micronaut.reactor)
    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.micronaut.inject.groovy)
    testImplementation(mnSecurity.micronaut.security)
    testImplementation(mnTest.micronaut.test.spock)
    testImplementation(projects.micronautOraclecloudBmcObjectstorage)
}
