plugins {
    id 'io.micronaut.build.internal.oraclecloud-module'
}

dependencies {
    api projects.micronautOraclecloudBmcCertificates
    implementation mn.micronaut.http.server.netty
    implementation mn.micronaut.inject.java
    implementation mn.micronaut.retry
    implementation(libs.bcpkixjdk15to18)
    compileOnly(mn.micronaut.http.client)

    api(libs.netty.codec.classes.quic)
    runtimeOnly(variantOf(libs.netty.codec.native.quic) { classifier("linux-x86_64") })
    runtimeOnly(variantOf(libs.netty.codec.native.quic) { classifier("linux-aarch_64") })
    runtimeOnly(variantOf(libs.netty.codec.native.quic) { classifier("osx-x86_64") })
    runtimeOnly(variantOf(libs.netty.codec.native.quic) { classifier("osx-aarch_64") })
    runtimeOnly(variantOf(libs.netty.codec.native.quic) { classifier("windows-x86_64") })

    testImplementation(mnSecurity.micronaut.security)
    testImplementation(mn.micronaut.http.client)
    testImplementation mnTest.micronaut.test.spock
    testImplementation mn.micronaut.inject.groovy
}


test {
    jvmArgs '-Djavax.net.debug=ssl,handshake,key'
}
