plugins {
    id 'io.micronaut.build.internal.oraclecloud-module'
}

dependencies {
    api projects.micronautOraclecloudBmcCertificates
    implementation mn.micronaut.http.server.netty
    implementation mn.micronaut.inject.java
    implementation mn.micronaut.retry
    implementation mnReactor.micronaut.reactor
    compileOnly(mn.micronaut.http.client)

    testImplementation(mnSecurity.micronaut.security)
    testImplementation(mn.micronaut.http.client)
    testImplementation mnTest.micronaut.test.spock
    testImplementation mn.micronaut.inject.groovy
}

