plugins {
    id 'io.micronaut.build.internal.oraclecloud-module'
}

dependencies {
    api(mn.micronaut.discovery.core)
    api(mn.micronaut.inject)
    api(projects.micronautOraclecloudBmcSecrets)
    api(projects.micronautOraclecloudBmcVault)
    implementation(mn.reactor)
    implementation(mnDiscoveryClient.micronaut.discovery.client)
    testImplementation(mnTest.micronaut.test.spock)
}
