package example

import com.oracle.bmc.disasterrecovery.DisasterRecoveryClient
import io.micronaut.context.annotation.Requires
import io.micronaut.test.extensions.junit5.annotation.MicronautTest
import jakarta.inject.Inject
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

// The client factory generated by @SdkImport creates the DisasterRecoveryClient with the mock
// authentication details provider of example.mock
@MicronautTest
@Requires(missingProperty = "micronaut.test.server.executable")
class SdkImportsTest {

    @Inject
    lateinit var disasterRecoveryClient: DisasterRecoveryClient

    @Test
    fun testImportedClient() {
        assertNotNull(disasterRecoveryClient)
    }
}
