plugins {
    id 'io.micronaut.build.internal.oraclecloud-module'
}

dependencies {
    api(mnKubernetes.micronaut.kubernetes.client.openapi.common)
    api(projects.micronautOraclecloudCommon)
    implementation(mnValidation.validation)
    implementation(projects.micronautOraclecloudBmcContainerengine)
    testImplementation(mn.micronaut.context)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mn.micronaut.inject.groovy)
    testImplementation(mn.micronaut.inject.groovy.test)
    testImplementation(mn.micronaut.inject.java)
    testImplementation(mnKubernetes.micronaut.kubernetes.client.openapi)
}

micronautBuild {
    binaryCompatibility {
        enabled = false
    }
}
