from typing import Annotated

from com.oracle.bmc.disasterrecovery import DisasterRecoveryClient
from jakarta.inject import Inject
from micronaut.test.extensions.junit5.annotation import MicronautTest
from org.junit.jupiter.api import Disabled, Test


# The client factory generated by @SdkImport creates the DisasterRecoveryClient with the mock
# authentication details provider of src/test/java (package mock)
@MicronautTest
@Disabled("TODO(python): @SdkImport is not processed on Python classes (Micronaut SourceGen has no Python source generator), see DISABLED_TESTS.md")
class SdkImportsTest:
    disaster_recovery_client: Annotated[DisasterRecoveryClient, Inject]

    @Test
    def test_imported_client(self) -> None:
        assert self.disaster_recovery_client is not None
