plugins {
    id 'io.micronaut.build.internal.oraclecloud-module'
    id("io.micronaut.build.internal.oraclecloud-bom")
}

dependencies {
    annotationProcessor projects.micronautOraclecloudSdkProcessor
    api(projects.micronautOraclecloudCommon) {
        exclude group: 'commons-logging', module: 'commons-logging'
    }
    api(projects.micronautOraclecloudHttpclientNetty)

    //https://ossindex.sonatype.org/vulnerability/CVE-2025-48924?component-type=maven&component-name=org.apache.commons%2Fcommons-lang3
    implementation(libs.commons.lang3)
    //https://ossindex.sonatype.org/vulnerability/CVE-2025-53864?component-type=maven&component-name=com.google.code.gson%2Fgson
    implementation(libs.gson)

    compileOnly(libs.graal.svm)
    compileOnly(mnRxjava2.rxjava2)
    compileOnly(projects.micronautOraclecloudSdkBase)
    testImplementation(libs.graal.svm)
    testImplementation(mnRxjava2.rxjava2)
    testImplementation(mnTest.micronaut.test.spock)

    // optional modules
    for (name in gradle.ociArtifacts) {
        String moduleName = name.toString()
        if (!moduleName.contains("examples") &&
                !moduleName.contains("-addons") &&
                !moduleName.contains("-common") &&
                !moduleName.endsWith("-enforcer-rules") &&
                !moduleName.endsWith("-full")) {
            annotationProcessor("com.oracle.oci.sdk:$name:$gradle.ociVersion")
            compileOnly("com.oracle.oci.sdk:$name:$gradle.ociVersion")
            testImplementation("com.oracle.oci.sdk:$name:$gradle.ociVersion")
        }
    }
}

spotlessJavaMiscCheck.enabled = false
compileJava.options.fork = true
compileJava.options.compilerArgs.add("-AociSdkClientClasses=$gradle.ociSdkClientClasses")

tasks.withType(me.champeau.gradle.japicmp.JapicmpTask) {
    // Ignore changes in the generated factories for the new OCI Java SDK
    packageExcludes = ["io.micronaut.oraclecloud.clients.*"]
}
