plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation(providers.gradleProperty("micronaut-build-version").map { "io.micronaut.build.internal:micronaut-kotlin-build-plugins:${it}" }.get())
    implementation(libs.micronaut.gradle.plugin)
    implementation(libs.protobuf.gradle.plugin)
    implementation(libs.shadow.plugin)
}
