plugins {
    id 'io.micronaut.build.internal.oraclecloud-module'
}

dependencies {
    api(libs.oci.oke.workload.identity)
    api(projects.micronautOraclecloudCommon)
    implementation(mn.reactor)
    implementation(libs.oci.common)
    implementation(mn.micronaut.http.client)
    implementation(projects.micronautOraclecloudHttpclientNetty)
    testImplementation(mn.micronaut.context)
    testImplementation(mnTest.mockito.core)
}

test {
    environment "KUBERNETES_SERVICE_HOST", "http://localhost"
}

micronautBuild {
    binaryCompatibility {
        int dash = version.indexOf('-')
        String v = dash > 0 ? version.substring(0, dash) : version
        def (major, minor, patch) = v.split('[.]').collect { it.toInteger() }
        enabled = major > 3 || (major == 3 && minor > 1) || (major == 3 && minor == 1 && patch > 0)
    }
}
