plugins {
    id 'io.micronaut.build.internal.oraclecloud-groovy-example'
}

dependencies {
    compileOnly(mnSerde.micronaut.serde.processor)
    implementation(mn.micronaut.http.server.netty)
    implementation(mnReactor.micronaut.reactor)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mnSerde.micronaut.serde.support)
    implementation(projects.micronautOraclecloudBmcDatabase)
    implementation(projects.micronautOraclecloudBmcObjectstorage)
    implementation(projects.micronautOraclecloudNotifications)
    runtimeOnly(mn.snakeyaml)
    runtimeOnly(mnLogging.logback.classic)
    testImplementation(libs.commons.lang3)
}

application {
    mainClass = 'example.Application'
}

test {
    exclude '**/*Test$Intercepted*'
}
