name: GraalVM CE CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graalvm: ['20.3.0.java8', '20.3.0.java11']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: ${{ matrix.graalvm }}
      - name: Install Native Image
        run: gu install native-image
      - name: Build with Gradle
        run: |
          if ./gradlew tasks --all | grep -w "testNativeImage"
          then
            ./gradlew check testNativeImage --continue --no-daemon
          else
            ./gradlew check --continue --no-daemon
          fi
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_TENANT_ID: ${{ secrets.OCI_TENANT_ID }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_PASSPHRASE: ${{ secrets.OCI_PASSPHRASE }}
          ATP_OCID: ${{ secrets.ATP_OCID }}
          ATP_USER: ${{ secrets.ATP_USER }}
          ATP_PASS: ${{ secrets.ATP_PASS }}
